// var QUERYSTRING_BLACKLIST = {
//     service: true,
//     version: true,
//     request: true,
//     exceptions: true,
//     layer: true,
//     layers: true,
//     styles: true,
//     srs: true,
//     crs: true,
//     width: true,
//     height: true,
//     format: true,
//     transparent: true,
//     bgcolor: true,
//     time: true,
//     sld: true,
//     sld_body: true,
//     query_layers: true,
//     info_format: true,
//     feature_count: true,
//     x: true,
//     i: true,
//     y: true,
//     j: true,
//     buffer: true,
//     cql_filter: true,
//     filter: true,
//     propertyname: true,
//     bbox: true,
//     outputFormat: true
// };

exports.syncable = false;
